### ISSUE TITLE
Remove coroutines

### ISSUE THREAD

**Issue by RobinCaroff** [mlumeau/workshop-kmp#8]
Coroutines seem to overcomplicate the workshop. 

I suggest removing coroutines from the Android project. The common code will use coroutines under the hood but will only expose interfaces with methods that take callbacks as parameters. No `suspend` functions exposed to the iOS and Android projects.

**Comment by RobinCaroff** [comment]
@mlumeau @ptibulle What do you think ?

**Comment by mlumeau** [comment]
@RobinCaroff How do you plan to hide the coroutines from participants ? They'll still have to implement them or else it will be another case of copy/paste step in the codelab.

**Comment by RobinCaroff** [comment]
@mlumeau We won't hide it. The common code will use coroutines but at least the Android code won't and we won't expose two methods with the interfaces with one not being implemented (the `suspend` one for iOS and the one using callbacks for Android).
I believe it will simplify a bit the workshop.
I can start working on a PR to show you what I mean.
